/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Tier Colors
        'tier1-ember': '#D4A017',
        'tier1-ember-secondary': '#8B4513',
        'tier1-ember-accent': '#FFD700',
        'tier2-verdant': '#2ECC71',
        'tier2-verdant-secondary': '#1B6B2E',
        'tier2-verdant-accent': '#39FF14',
        'tier3-abyssal': '#1ABC9C',
        'tier3-abyssal-secondary': '#0D4F4F',
        'tier3-abyssal-accent': '#00E5FF',
        'tier4-void': '#8E44AD',
        'tier4-void-secondary': '#4A1A6B',
        'tier4-void-accent': '#E040FB',
        'tier5-deepspace': '#2980B9',
        'tier5-deepspace-secondary': '#0C1445',
        'tier5-deepspace-accent': '#00BFFF',
        // Global Colors
        'bg-base': '#0A0A0F',
        'bg-panel': '#14141E',
        'bg-elevated': '#1E1E2E',
        'bg-hud': 'rgba(10,10,15,0.92)',
        'text-primary': '#E8E0D0',
        'text-secondary': '#9B8B7A',
        'text-muted': '#5C5346',
        'text-gold': '#D4A017',
        'border-default': 'rgba(232,224,208,0.12)',
        'border-active': 'rgba(212,160,23,0.5)',
        'accent-damage': '#E74C3C',
        'accent-heal': '#2ECC71',
        'accent-combo': '#FFD700',
        'accent-wipe': '#FFFFFF',
        'rune-glow': 'rgba(212,160,23,0.3)',
      },
      fontFamily: {
        cinzel: ['Cinzel', 'serif'],
        inter: ['Inter', 'sans-serif'],
        'fira-code': ['Fira Code', 'monospace'],
        medieval: ['MedievalSharp', 'cursive'],
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
        'radius-sm': '4px',
        'radius-md': '8px',
        'radius-lg': '12px',
        'radius-pill': '9999px',
        'radius-circle': '50%',
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        'input-glow-correct': '0 0 12px rgba(46,204,113,0.6), 0 0 4px rgba(46,204,113,0.3)',
        'input-glow-wrong': '0 0 12px rgba(231,76,60,0.6), 0 0 4px rgba(231,76,60,0.3)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "damage-pop": {
          "0%": { transform: "scale(0.5) translateY(0)", opacity: "1" },
          "50%": { transform: "scale(1.3) translateY(-20px)", opacity: "1" },
          "100%": { transform: "scale(1.0) translateY(-40px)", opacity: "0" },
        },
        "screen-shake": {
          "0%, 100%": { transform: "translateX(0)" },
          "10%": { transform: "translateX(-8px)" },
          "20%": { transform: "translateX(8px)" },
          "30%": { transform: "translateX(-8px)" },
          "40%": { transform: "translateX(8px)" },
          "50%": { transform: "translateX(-8px)" },
          "60%": { transform: "translateX(8px)" },
          "70%": { transform: "translateX(-8px)" },
          "80%": { transform: "translateX(8px)" },
          "90%": { transform: "translateX(-8px)" },
        },
        "combo-flash": {
          "0%": { backgroundColor: "rgba(255,215,0, 0)" },
          "30%": { backgroundColor: "rgba(255,215,0, 0.3)" },
          "100%": { backgroundColor: "rgba(255,215,0, 0)" },
        },
        "antonym-wipe": {
          "0%": { backgroundColor: "rgba(255,255,255, 0)" },
          "50%": { backgroundColor: "rgba(255,255,255, 0.8)" },
          "100%": { backgroundColor: "rgba(255,255,255, 0)" },
        },
        "word-glow": {
          "0%, 100%": { boxShadow: "0 0 8px rgba(212,160,23,0.2)" },
          "50%": { boxShadow: "0 0 20px rgba(212,160,23,0.5)" },
        },
        "rune-float": {
          "0%, 100%": { transform: "translateY(0) rotate(0deg)" },
          "50%": { transform: "translateY(-6px) rotate(3deg)" },
        },
        "monster-idle": {
          "0%, 100%": { transform: "scale(1.0)" },
          "50%": { transform: "scale(1.02)" },
        },
        "monster-hit": {
          "0%, 100%": { transform: "translateX(0)", filter: "brightness(1)" },
          "20%": { transform: "translateX(-5px)", filter: "brightness(2) saturate(0.5)" },
          "40%": { transform: "translateX(5px)", filter: "brightness(1.5)" },
          "60%": { transform: "translateX(-5px)", filter: "brightness(2) saturate(0.5)" },
          "80%": { transform: "translateX(5px)", filter: "brightness(1)" },
        },
        "monster-defeat": {
          "0%": { transform: "scale(1.0) rotate(0deg)", opacity: "1" },
          "100%": { transform: "scale(0.3) rotate(15deg)", opacity: "0" },
        },
        "timer-deplete": {
          "0%": { width: "100%" },
          "100%": { width: "0%" },
        },
        "ember-float": {
          "0%": { transform: "translateY(100vh) translateX(0)", opacity: "0" },
          "10%": { opacity: "0.6" },
          "90%": { opacity: "0.3" },
          "100%": { transform: "translateY(-100px) translateX(50px)", opacity: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "damage-pop": "damage-pop 700ms cubic-bezier(0.34, 1.56, 0.64, 1) forwards",
        "screen-shake": "screen-shake 400ms ease-in-out",
        "combo-flash": "combo-flash 500ms ease-out",
        "antonym-wipe": "antonym-wipe 400ms ease-out",
        "word-glow": "word-glow 2s cubic-bezier(0.37, 0, 0.63, 1) infinite",
        "rune-float": "rune-float 4s cubic-bezier(0.37, 0, 0.63, 1) infinite",
        "monster-idle": "monster-idle 3s cubic-bezier(0.37, 0, 0.63, 1) infinite",
        "monster-hit": "monster-hit 300ms ease-in-out",
        "monster-defeat": "monster-defeat 800ms cubic-bezier(0.7, 0, 0.84, 0) forwards",
        "timer-deplete": "timer-deplete 3s linear forwards",
        "ember-float": "ember-float 12s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
